# Generated by Django 5.2.6 on 2025-11-25 23:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='rank',
            field=models.CharField(choices=[('bronze', 'Bronze'), ('silver', 'Silver'), ('gold', 'Gold'), ('platinum', 'Platinum'), ('diamond', 'Diamond'), ('champion', 'Champion')], default='bronze', max_length=20),
        ),
        migrations.AddField(
            model_name='profile',
            name='show_admin_status',
            field=models.BooleanField(default=True),
        ),
    ]
